name: Go
on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
  workflow_call:
jobs:
  self-tests:
    name: Selftests
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        go-version: [ 'stable' ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Dependencies
        uses: ./.github/actions/build-dependencies
        with:
          go-version: ${{ matrix.go-version }}
      - name: Static Selftests
        run: |
          make dep
          git submodule init
          git submodule sync
          git submodule update
          cd scx
          meson setup build --prefix ~
          meson compile -C build
          cd ..
          cd libbpfgo
          make
          cd ..
          make build
          make test
        shell: bash